# *********************************************** Scenario: Create Replicaset in Kubernetes Cluster **********************************************

# The Nautilus DevOps team is going to deploy some applications on kubernetes cluster as they are planning to migrate some of their existing applications there. Recently one of the team members has been assigned a task to write a template as per details mentioned below:

# Create a ReplicaSet using nginx image with latest tag only and remember to mention tag i.e nginx:latest and name it as nginx-replicaset.

# Labels app should be nginx_app, labels type should be front-end. The container should be named as nginx-container; also make sure replicas counts are 4.

# Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.

# -------------------------------------------------------------------------------------------------------------------------------------------
# Solution:
# 1. At first  kubectl  utility configure and working from jump server, run below commands 
# kubectl get all 

# 2.  Create yaml  file with all the parameters   

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx_app
    type: front-end
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      labels:
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
		
# 3.  Run the below command to create a pod   	
# kubectl apply -f <file-name>

# 4.  Wait for  pods to get running status
# kubectl get all

