# ************************************************** Scenario: Create Deployments in Kubernetes Cluster *************************************

# The Nautilus DevOps team has started practicing some pods, and services deployment on Kubernetes platform, as they are planning to migrate most of their applications on Kubernetes. Recently one of the team members has been assigned a task to create a deploymnt as per details mentioned below:

# Create a deployment named nginx to deploy the application nginx using the image nginx:latest (remember to mention the tag as well)

# Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.
# ------------------------------------------------------------------------------------------------------------------------------------------
# Solution:

# 1. At first  kubectl  utility configure and working from jump server, run below commands 
# kubectl get all 

# 2. Create deployment with the specs given

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
		
# 3.  Run the below command to create a pod   	
# kubectl apply -f <deployment-file-name>

# 4.  Wait for  pods to get running status
# kubectl get all

# 5. Click on Finish & Confirm to complete the task successful	

