# **************************************************** Scenario: Deploy Tomcat App on Kubernetes *************************************************

# A new java-based application is ready to be deployed on a Kubernetes cluster. The development team had a meeting with the DevOps team share requirements and application scope. The team is ready to setup an application stack for it under their existing cluster. Below you can find the details for this:

# Create a namespace named tomcat-namespace-devops.

# Create a deployment for tomcat app which should be named tomcat-deployment-devops under the same namespace you created. Replicas count should be 1, the container should be named as tomcat-container-devops, its image should be gcr.io/kodekloud/centos-ssh-enabled:tomcat and its container port should be 8080.

# Create a service for tomcat app which should be named as tomcat-service-devops under the same namespace you created. Service type should be NodePort. Port's protocol should be TCP, port should be 80, targetPort should be 8080 and nodePort should be 32227.

# Before clicking on Finish button please make sure the application is up and running.

# You can use any labels as per your choice.

# Note: The kubectl on jump_host has been configured to work with the kubernetes cluster.
 
# -------------------------------------------------------------------------------------------------------------------------------------

# 1. Create namespace
# kubectl create ns tomcat-namespace-devops

# 2. Create Deployment

# vi tomcat-deployment-devops.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-devops
  namespace: tomcat-namesapce-devops
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container-devops
        image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
		ports:
        - containerPort: 8080

		
---

# 3. Create service 

# vi tomcat-service-devops.yml

apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-devops
  namespace: tomcat-namespace-devops
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32227
	  
# 4. Execute the changes

# kubeclt apply -f tomcat-deployment-devops.yml -n grafana-monitoring-xfusion --dry-run=client
# kubeclt apply -f tomcat-deployment-devops.yml -n grafana-monitoring-xfusion

# kubeclt apply -f grafana-service-devops-service.yml -n grafana-monitoring-xfusion --dry-run=client
# kubeclt apply -f grafana-service-devops-service.yml -n grafana-monitoring-xfusion

# 5. Test changes

#Test with NodePort 32227 on the browser
