# *********************************************** Scenario: Init Containers in Kubernetes **************************************************

# There are some applications that need to be deployed on Kubernetes cluster and these apps have some pre-requisites where some configurations need to be changed before deploying the app container. Some of these changes cannot be made inside the images so the DevOps team has come up with a solution to use init containers to perform these tasks during deployment. Below is a sample scenario that the team is going to test first.

# Create a Deployment named as ic-deploy-datacenter.

# Configure spec as replicas should be 1, labels app should be ic-datacenter, template's metadata lables app should be the same ic-datacenter.

# The initContainers should be named as ic-msg-datacenter, use image ubuntu, preferably with latest tag and use command '/bin/bash', '-c' and 'echo Init Done - Welcome to xFusionCorp Industries > /ic/blog'. The volume mount should be named as ic-volume-datacenter and mount path should be /ic.

# Main container should be named as ic-main-datacenter, use image ubuntu, preferably with latest tag and use command '/bin/bash', '-c' and 'while true; do cat /ic/blog; sleep 5; done'. The volume mount should be named as ic-volume-datacenter and mount path should be /ic.

# Volume to be named as ic-volume-datacenter and it should be an emptyDir type.

# Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.

# -------------------------------------------------------------------------------------------------------------------------------------------
# Solution:

# 1. write deployment yaml file based on the specifications

# vi /home/thor/ic-deploy-datacenter-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-deploy-datacenter
  labels:
    app: ic-datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-datacenter
  template:
    metadata:
      labels:
        app: ic-datacenter
    spec:
      volumes:
        - name: ic-volume-datacenter
          emptyDir: {}
      initContainers:
        - name: ic-msg-datacenter
          image: ubuntu:latest
          command:
            [
              "/bin/bash",
              "-c",
              "echo Init Done - Welcome to xFusionCorp Industries > /ic/blog",
            ]
          volumeMounts:
            - name: ic-volume-datacenter
              mountPath: /ic

      containers:
        - name: ic-main-datacenter
          image: ubuntu:latest
          command:
            [
              "/bin/bash",
              "-c",
              "while true; do cat /ic/blog; sleep 5; done",
            ]
          volumeMounts:
            - name: ic-volume-datacenter
              mountPath: /ic		

# 2. compile and execute the yml file

# kubectl apply -f ic-deploy-datacenter-deployment.yml --dry-run=client

# kubectl apply -f ic-deploy-datacenter-deployment.yml

# 3. Test the changes 

# kubectl exec -it ic-deploy-xfusion-xxxxx -- /bin/bash
# In the resulting prompt, type 'cat /ic/official' and you should
# see "Init Done - Welcome to xFusionCorp Industries"

# Verify: kubectl logs -f ic-deploy-xfusion-xxxxx
# You should see the message "Init Done - Welcome to xFusionCorp Industries"
# printed every 5 secs

