# ******************************************** Scenario: Kubernetes Time Check Pod *******************************************************

# The Nautilus DevOps team want to create a time check pod in a particular Kubernetes namespace and record the logs. This might be initially used only for testing purposes, but later can be implemented in an existing cluster. Please find more details below about the task and perform it.

# Create a pod called time-check in the nautilus namespace. This pod should run a container called time-check, container should use the busybox image with latest tag only and remember to mention tag i.e busybox:latest.

# Create a config map called time-config with the data TIME_FREQ=3 in the same namespace.

# The time-check container should run the command: while true; do date; sleep $TIME_FREQ;done and should write the result to the location /opt/dba/time/time-check.log. Remember you will also need to add an environmental variable TIME_FREQ in the container, which should pick value from the config map TIME_FREQ key.

# Create a volume log-volume and mount the same on /opt/dba/time within the container.

# Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.

# -------------------------------------------------------------------------------------------------------------------------------------------
# 1. Check existing running Pods  & Services 
# kubectl get all

# 2. Create a YAML  file with all the parameters, Kindly do the changes as per task

# ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: nautilus
data:
 TIME_FREQ: "3"
  
---

# Pod

apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: nautilus
  labels:
    app: time-check
spec:
  containers:
    - name: time-check
      image: busybox:latest
      command: ["/bin/sh"]
	  args: ["-c", "while true; do date; sleep $TIME_FREQ;done >> /opt/dba/time/time-check.log"]
      env:
      - name: TIME_FREQ
	    valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
	  volumeMounts:
      - name: log-volume
        mountPath: "/opt/dba/time"
  volumes:
  - name: log-volume
    emptyDir: {}  
			  
  
# 3.  Run the below command to create a pod   	
# kubectl apply -f <file-name>

# 4.  Wait for  pods to get running status and check container logs
# kubectl get all -n nautilus
# kubectl exec -n nautilus time-check -c time-check -- sh
# tail -f /opt/dba/time/time-check.log




  